# Generated by Django 4.1.5 on 2023-01-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='hour',
            field=models.DateTimeField(),
        ),
    ]
