# Generated by Django 4.1.5 on 2023-01-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_cpf_alter_transactions_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
    ]
